name: dw3_pizz_delivery_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  build_runner: ^1.11.1
  dotenv: ^2.0.0
  get_it: ^5.0.6
  injectable: ^1.0.7
  mysql1: ^0.17.1
  shelf: ^0.7.5

dev_dependencies:
  injectable_generator: ^1.0.7
  pedantic: ^1.9.0
